name: Github Deployment
on:
  workflow_dispatch:
jobs:
  ctoai-metrics:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: 'Deploy Dummy'
        run: |
          echo "noop"